### ISSUE TITLE
No fixed Redis version in container image

### ISSUE THREAD

**Issue by ppxl** [cloudogu/redis#5]
The Dockerfile does not pin the used version of Redis. This should be fixed for two reasons:

1. when the Alpine image changes (usually under the hood), the dogu version reflects a false redis version
   - f. e. `6.2.6-2` != `6.3.1`
1. when the base image changes, the redis package will probably change to a major version
   - different major version may introduce new behavior and/or remove features which may disturb the production environment for dogus which rely on a certain behaviour/feature

**Comment by kahoona77** [comment]
resolved by #6
